### ISSUE TITLE
[nsfw] Bug report

### ISSUE THREAD

**Issue by theMisteryDE** [Chii-Onan/onii-cogs#102]
**Describe the bug**
Since a couple of days none of the nsfw commands seem to work. Everytime someone tries it, an "error in command...." occurs. Couldn't find a solution, even deleting and reinstalling the repo didn't help

**Bot's logs**
Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/lady_red/cogs/CogManager/cogs/nsfw/nsfw.py", line 452, in _anal
    embed.set_image(url=await api_call("https://nekos.life/api/v2/img/anal"))
  File "/root/.local/share/Red-DiscordBot/data/lady_red/cogs/CogManager/cogs/nsfw/nsfw.py", line 31, in api_call
    return response["url"]
KeyError: 'url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 832, in invoke
    await super().invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1348, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'url'

**Red version**
3.4.16

**Comment by Chii-Onan** [comment]
Thank you foe submitting this issue, this error is occurring because nekos.life, the API we use for some parts of the nsfw cog has removed all nsfw endpoints. This means that we can no longer fetch nsfw images from them. I will try to find another API for hentai images but until then I'd suggest you either disable all hentai commands or unload the cog.

**Comment by Chii-Onan** [comment]
Hi, sorry for the late update, but I no longer have an interest in maintaining the nsfw cog and as such unless somebody pr's a fix for this, I will not be fixing it right now. I might get back to it at a later point, but currently my attention is focused elsewhere.

I sincerely apologize for an inconvenience caused and suggest that all users should migrate to another nsfw cog like Preda's.
